source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target ‘DATING’ do
    
    pod 'Alamofire', '~> 4.4'
    pod 'AlamofireImage', '~> 3.1'
    pod 'ObjectMapper', '2.2.2'
    pod 'GzipSwift', '3.1.2'
    pod 'SVProgressHUD', '2.0.3'
    pod 'MJRefresh'
    pod 'MessageDisplayKit'
    pod 'XHPopMenu'
    pod 'SDWebImage', '~> 3.8.1'
    pod 'IQKeyboardManagerSwift', '4.0.6'
    pod 'WechatOpenSDK'
    

    pod 'Reachability', '~> 3.1.1'
    pod 'Toast', '~> 3.0'
    pod 'SVProgressHUD', '~> 2.0.3'
#    pod 'M80AttributedLabel', '~> 1.6.3'

#    pod 'TZImagePickerController'
end
